name: "naamio"

# cspell:ignore initdb, tmpfs, maildir

services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_root_password_123
    ports:
      - 6206:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  mailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /data
    ports:
      - 6208:1025
      - 6207:8025
    volumes:
      - mailhog_data:/data

volumes:
  postgres_data:
  mailhog_data:
