name: "naamio"

# cspell:ignore initdb, tmpfs, axllent, caddyfile, orbstack

services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_root_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  mailpit:
    image: axllent/mailpit:v1.28.0
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - mailpit_data:/data

  otel-lgtm:
    image: grafana/otel-lgtm:0.13.0
    volumes:
      - otel_data:/data

  caddy:
    image: caddy:2.10.2-alpine
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    labels:
      - dev.orbstack.domains=janus.naamio.orb.local,mercury.naamio.orb.local,minerva.naamio.orb.local,vulcan.naamio.orb.local

volumes:
  postgres_data:
  mailpit_data:
  otel_data:
