name: ğŸ§‘â€ğŸ”¬ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

permissions:
  contents: read

jobs:
  verify:
    name: ğŸ”¬ Verify
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm turbo run build lint typecheck sort-package-json spellcheck format test effect-diagnostics --continue

  boundaries:
    name: ğŸ›‚ Boundaries
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm turbo boundaries

  codegen:
    name: âš™ï¸ Codegen
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm codegen

      - name: Verify
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "âŒ ERROR: Uncommitted changes detected after executing codegen"
            echo "ğŸ’¡ The following files were modified:"
            git status --porcelain
            echo "âœ¨ Make sure to run all codegen tasks before committing and push all up-to-date files"
            exit 1
          fi
